# Generated by Django 4.1.4 on 2023-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_detail',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
