# Generated by Django 4.1.4 on 2023-02-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_temp_detail_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_detail',
            name='otp',
            field=models.CharField(default=True, max_length=6),
        ),
    ]
